### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by sweetalidinesh** [hyperledger/composer-vscode-plugin#80]
Composer plugin crash with error even though lodash snippet is installed.
VSCode Details :
Version 1.24.0
Date 2018-06-06T17:35:02.816Z
Node 7.9.0
Architecture ia32

Error: Cannot find module 'lodash'
at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\sweetalidinesh\.vscode\extensions\hyperledgercomposer.composer-support-client-0.19.5\server\node_modules\composer-common\lib\cardstore\walletbackedcardstore.js:24:11)
    at Object.<anonymous> (c:\Users\sweetalidinesh\.vscode\extensions\hyperledgercomposer.composer-support-client-0.19.5\server\node_modules\composer-common\lib\cardstore\walletbackedcardstore.js:152:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Info  - 11:02:40 AM] Connection to server got closed. Server will restart.
module.js:472
    throw err;

**Comment by m-g-k** [comment]
Hi, thanks for the report - I'll try and push a new version with a fix out later today

**Comment by m-g-k** [comment]
This was caused by an underlying problem in the composer-common library used by the plugin and has already been fixed there. So just updating the plugin to use the latest composer-common has fixed this. Please install the v0.19.8 version which includes the fix. This has just been pushed to the marketplace so the install should happen automatically.
